# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from mistapi.api_helper import APIHelper
from mistapi.models.site_setting import SiteSetting
from mistapi.models.model_object_macs_array_string import ModelObjectMacsArrayString


class SitesSettingControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(SitesSettingControllerTests, cls).setUpClass()
        cls.controller = cls.client.sites_setting
        cls.response_catcher = cls.controller.http_call_back

    # Get Site Settings
    def test_get_site_setting(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.get_site_setting(site_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"additional_config_cmds":["string"],"analytic":{"enabled":false},'
            '"auto_upgrade":{"custom_versions":{"property1":"string","property2'
            '":"string"},"day_of_week":"any","enabled":false,"time_of_day":"str'
            'ing","version":"stable"},"bgp_groups":{"property1":{"type":"extern'
            'al"},"property2":{"type":"external"}},"ble_config":{"beacon_enable'
            'd":true,"beacon_rate":0,"beacon_rate_mode":"default","beam_disable'
            'd":[0],"eddystone_uid_adv_power":-100,"eddystone_uid_beams":"strin'
            'g","eddystone_uid_enabled":true,"eddystone_uid_freq_msec":0,"eddys'
            'tone_uid_instance":"string","eddystone_uid_namespace":"string","ed'
            'dystone_url_adv_power":0,"eddystone_url_beams":"string","eddystone'
            '_url_enabled":true,"eddystone_url_freq_msec":0,"eddystone_url_url"'
            ':"string","ibeacon_adv_power":-100,"ibeacon_beams":"string","ibeac'
            'on_enabled":false,"ibeacon_freq_msec":0,"ibeacon_major":0,"ibeacon'
            '_minor":0,"ibeacon_uuid":"1f89bc00-d0af-481b-82fe-a6629259a39f","p'
            'ower":9,"power_mode":"string"},"config_auto_revert":false,"created'
            '_time":0,"device_updown_threshold":0,"dns_servers":["string"],"dns'
            '_suffix":["string"],"enable_channel_144":false,"engagement":{"dwel'
            'l_tag_names":{"bounce":"string","engaged":"string","passerby":"str'
            'ing","stationed":"string"},"dwell_tags":{"bounce":"string","engage'
            'd":"string","passerby":"string","stationed":"string"},"hours":{"fr'
            'i":"string","mon":"string","sta":"string","sun":"string","thu":"st'
            'ring","tue":"string","wed":"string"},"max_dwell":43200,"min_dwell"'
            ':0},"evpn_options":{"overlay":{"as":0},"underlay":{"as_base":0,"su'
            'bnet":"string"}},"flags":{"property1":"string","property2":"string'
            '"},"for_site":true,"gateway_mgmt":{"app_usage":true,"config_revert'
            '_timer":10},"id":"458f6ec2-6276-4993-bfeb-53abbbba6f08","led":{"br'
            'ightness":0,"enabled":true},"modified_time":0,"mxtunnels":{"proper'
            'ty1":{"ap_subnets":["string"],"clusters":[{"name":"string","tunter'
            'm_hosts":["string"]}],"created_time":0,"for_site":true,"hello_inte'
            'rval":60,"hello_retries":7,"hosts":["string"],"id":"457f6ec3-6276-'
            '4993-bfeb-53cbbbba6f08","modified_time":0,"mtu":0,"org_id":"a40f5d'
            '1f-d889-42e9-94ea-b9b33585fc6b","protocol":"udp","radsec":{"acct_s'
            'ervers":[{"host":"string","port":1813,"secret":"string"}],"auth_se'
            'rvers":[{"host":"string","port":1812,"secret":"string"}],"enabled"'
            ':true,"use_mxedge":true},"site_id":"72771e6a-6f5e-4de4-a5b9-1266c4'
            '197811","vlan_ids":[0]},"property2":{"ap_subnets":["string"],"clus'
            'ters":[{"name":"string","tunterm_hosts":["string"]}],"created_time'
            '":0,"for_site":true,"hello_interval":60,"hello_retries":7,"hosts":'
            '["string"],"id":"456f6ec4-6276-4993-bfeb-53cbbbba6f08","modified_t'
            'ime":0,"mtu":0,"org_id":"a40f5d1f-d889-42e9-94ea-b9b33585fc6b","pr'
            'otocol":"udp","radsec":{"acct_servers":[{"host":"string","port":18'
            '13,"secret":"string"}],"auth_servers":[{"host":"string","port":181'
            '2,"secret":"string"}],"enabled":true,"use_mxedge":true},"site_id":'
            '"72771e6a-6f5e-4de4-a5b9-1266c4197811","vlan_ids":[0]}},"networks"'
            ':{"property1":{"dns":["string"],"dns_suffix":["string"],"gateway":'
            '"string","ospf_interface_type":"string","subnet":"string","vlan_id'
            '":0,"zone":"string"},"property2":{"dns":["string"],"dns_suffix":["'
            'string"],"gateway":"string","ospf_interface_type":"string","subnet'
            '":"string","vlan_id":0,"zone":"string"}},"ntp_servers":["string"],'
            '"occupancy":{"assets_enabled":false,"clients_enabled":true,"min_du'
            'ration":3000,"sdkclients_enabled":false,"unconnected_clients_enabl'
            'ed":false},"org_id":"a40f5d1f-d889-42e9-94ea-b9b33585fc6b","ospf_a'
            'reas":{"property1":{"networks":{"property1":{"auth_keys":{"propert'
            'y1":"string","property2":"string"},"auth_password":"string","auth_'
            'type":"none","interface_type":"nbma","passive":false},"property2":'
            '{"auth_keys":{"property1":"string","property2":"string"},"auth_pas'
            'sword":"string","auth_type":"none","interface_type":"nbma","passiv'
            'e":false}},"type":"default"},"property2":{"networks":{"property1":'
            '{"auth_keys":{"property1":"string","property2":"string"},"auth_pas'
            'sword":"string","auth_type":"none","interface_type":"nbma","passiv'
            'e":false},"property2":{"auth_keys":{"property1":"string","property'
            '2":"string"},"auth_password":"string","auth_type":"none","interfac'
            'e_type":"nbma","passive":false}},"type":"default"}},"persist_confi'
            'g_on_device":false,"port_usages":{"dynamic":{"mode":"dynamic","rul'
            'es":[{"equals":"string","expression":"string","src":"lldp_chassis_'
            'id","usage":"string"}]},"property1":{"all_networks":false,"bypass_'
            'auth_when_server_down":true,"description":"string","disable_autone'
            'g":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"default'
            '_network":0,"enabled":true,"networks":{"property1":0,"property2":0'
            '},"type":"standard"},"enable_mac_auth":true,"enable_qos":true,"gue'
            'st_network":"string","mac_limit":0,"mode":"access","mtu":0,"networ'
            'ks":["string"],"persist_mac":false,"poe_disabled":false,"port_auth'
            '":"string","port_network":"string","speed":"string","storm_control'
            '":{"no_broadcast":false,"no_multicast":false,"no_registered_multic'
            'ast":false,"no_unknown_unicast":false,"percentage":80},"stp_edge":'
            'true,"voip_network":"string"},"property2":{"all_networks":false,"b'
            'ypass_auth_when_server_down":true,"description":"string","disable_'
            'autoneg":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"d'
            'efault_network":0,"enabled":true,"networks":{"property1":0,"proper'
            'ty2":0},"type":"standard"},"enable_mac_auth":true,"enable_qos":tru'
            'e,"guest_network":"string","mac_limit":0,"mode":"access","mtu":0,"'
            'networks":["string"],"persist_mac":false,"poe_disabled":false,"por'
            't_auth":"string","port_network":"string","speed":"string","storm_c'
            'ontrol":{"no_broadcast":false,"no_multicast":false,"no_registered_'
            'multicast":false,"no_unknown_unicast":false,"percentage":80},"stp_'
            'edge":true,"voip_network":"string"}},"proxy":{"url":"string"},"rad'
            'io_config":{"ant_gain_24":0,"ant_gain_5":0,"band_24":{"allow_rrm_d'
            'isable":true,"ant_gain":0,"antenna_mode":"default","bandwidth":20,'
            '"channel":0,"channels":[0],"disabled":true,"power":0,"power_max":0'
            ',"power_min":0,"preamble":"short","usage":"24"},"band_24_usage":"2'
            '4","band_5":{"allow_rrm_disable":true,"ant_gain":0,"antenna_mode":'
            '"default","bandwidth":20,"channel":0,"channels":[0],"disabled":tru'
            'e,"power":0,"power_max":0,"power_min":0,"preamble":"short","usage"'
            ':"24"},"band_5_on_24_radio":{"allow_rrm_disable":true,"ant_gain":0'
            ',"antenna_mode":"default","bandwidth":20,"channel":0,"channels":[0'
            '],"disabled":true,"power":0,"power_max":0,"power_min":0,"preamble"'
            ':"short","usage":"24"},"scanning_enabled":true},"radius_config":{"'
            'acct_interim_interval":0,"acct_servers":[{"host":"string","port":1'
            '813,"secret":"string"}],"auth_servers":[{"host":"string","port":18'
            '12,"secret":"string"}],"auth_servers_retries":3,"auth_servers_time'
            'out":5},"remote_syslog":{"enabled":true,"send_to_all_servers":true'
            ',"servers":[{"facility":"any","host":"string","port":0,"protocol":'
            '"udp","severity":"alert","tag":"string"}]},"report_gatt":false,"ro'
            'gue":{"enabled":true,"honeypot_enabled":true,"min_duration":10,"mi'
            'n_rssi":-80,"whitelisted_bssids":["string"],"whitelisted_ssids":["'
            'string"]},"rtsa":{"app_waking":false,"disable_dead_reckoning":true'
            ',"disable_pressure_sensor":true,"enabled":true,"track_asset":true}'
            ',"site_id":"72771e6a-6f5e-4de4-a5b9-1266c4197811","skyatp":{"enabl'
            'ed":true,"send_ip_mac_mapping":true},"ssh_keys":["string"],"status'
            '_portal":{"enabled":true,"hostnames":["string"]},"switch_matching"'
            ':{"enable":true,"rules":[{"additional_config_cmds":["string"],"nam'
            'e":"string","port_config":{"property1":{"ae_disable_lacp":true,"ae'
            '_idx":0,"aggregated":false,"description":"string","esilag":true,"u'
            'sage":"string"},"property2":{"ae_disable_lacp":true,"ae_idx":0,"ag'
            'gregated":false,"description":"string","esilag":true,"usage":"stri'
            'ng"}},"property1":"string","property2":"string"}]},"switch_mgmt":{'
            '"config_revert_timer":10,"root_password":"string"},"track_anonymou'
            's_devices":false,"vars":{"property1":"string","property2":"string"'
            '},"vrf_instances":{"property1":{"extra_routes":{"property1":{"via"'
            ':"192.168.0.1"},"property2":{"via":"192.168.0.1"}},"networks":["st'
            'ring"]},"property2":{"extra_routes":{"property1":{"via":"192.168.0'
            '.1"},"property2":{"via":"192.168.0.1"}},"networks":["string"]}},"v'
            'rrp_groups":{"property1":{"auth_key":"string","auth_password":"str'
            'ing","auth_type":"md5","networks":{"property1":{"ip":"string"},"pr'
            'operty2":{"ip":"string"}}},"property2":{"auth_key":"string","auth_'
            'password":"string","auth_type":"md5","networks":{"property1":{"ip"'
            ':"string"},"property2":{"ip":"string"}}}},"wids":{"repeated_auth_f'
            'ailures":{"duration":0,"threshold":0}},"wifi":{"cisco_enabled":tru'
            'e,"disable_11k":false,"disable_radios_when_power_constrained":true'
            ',"enable_arp_spoof_check":false,"enable_channel_144":false,"enable'
            '_shared_radio_scanning":true,"enable_vna":false,"enabled":true,"lo'
            'cate_connected":false,"locate_unconnected":false,"mesh_allow_dfs":'
            'false,"mesh_enabled":false,"proxy_arp":"default"},"zone_occupancy_'
            'alert":{"email_notifiers":["string"],"enabled":false,"threshold":5'
            '}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Update Site Settings
    def test_update_site_settings(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"additional_config_cmds":["string"],"analytic":{"enabled":false},'
            '"ap_matching":{"enabled":true,"rules":[{"match_model":"string","na'
            'me":"string","port_config":{"property1":{"disabled":true,"dynamic_'
            'vlan":{"default_vlan_id":0,"enabled":true,"type":"string","vlans":'
            '{"property1":"string","property2":"string"}},"enable_mac_auth":tru'
            'e,"forwarding":"all","mx_tunnel_id":"5f5cac07-0805-46ea-aafd-5c572'
            '9042729","mxtunnel_name":"string","port_auth":"none","port_vlan_id'
            '":0,"radius_config":{"acct_interim_interval":0,"acct_servers":[{"h'
            'ost":"string","port":1813,"secret":"string"}],"auth_servers":[{"ho'
            'st":"string","port":1812,"secret":"string"}],"auth_servers_retries'
            '":3,"auth_servers_timeout":5,"coa_enabled":false,"coa_port":3799,"'
            'network":"string","source_ip":"string"},"radsec":{"enabled":true,"'
            'idle_timeout":0,"server_name":"string","servers":[{"host":"string"'
            ',"port":0}],"use_mxedge":true},"vlan_id":0,"vland_ids":[0],"wxtunn'
            'el_id":"string","wxtunnel_remote_id":"string"},"property2":{"disab'
            'led":true,"dynamic_vlan":{"default_vlan_id":0,"enabled":true,"type'
            '":"string","vlans":{"property1":"string","property2":"string"}},"e'
            'nable_mac_auth":true,"forwarding":"all","mx_tunnel_id":"5f5cac07-0'
            '805-46ea-aafd-5c5729042729","mxtunnel_name":"string","port_auth":"'
            'none","port_vlan_id":0,"radius_config":{"acct_interim_interval":0,'
            '"acct_servers":[{"host":"string","port":1813,"secret":"string"}],"'
            'auth_servers":[{"host":"string","port":1812,"secret":"string"}],"a'
            'uth_servers_retries":3,"auth_servers_timeout":5,"coa_enabled":fals'
            'e,"coa_port":3799,"network":"string","source_ip":"string"},"radsec'
            '":{"enabled":true,"idle_timeout":0,"server_name":"string","servers'
            '":[{"host":"string","port":0}],"use_mxedge":true},"vlan_id":0,"vla'
            'nd_ids":[0],"wxtunnel_id":"string","wxtunnel_remote_id":"string"}}'
            '}]},"ap_port_config":{"model_specific":{"property1":{"property1":{'
            '"disabled":true,"dynamic_vlan":{"default_vlan_id":0,"enabled":true'
            ',"type":"string","vlans":{"property1":"string","property2":"string'
            '"}},"enable_mac_auth":true,"forwarding":"all","mx_tunnel_id":"5f5c'
            'ac07-0805-46ea-aafd-5c5729042729","mxtunnel_name":"string","port_a'
            'uth":"none","port_vlan_id":0,"radius_config":{"acct_interim_interv'
            'al":0,"acct_servers":[{"host":"string","port":1813,"secret":"strin'
            'g"}],"auth_servers":[{"host":"string","port":1812,"secret":"string'
            '"}],"auth_servers_retries":3,"auth_servers_timeout":5,"coa_enabled'
            '":false,"coa_port":3799,"network":"string","source_ip":"string"},"'
            'radsec":{"enabled":true,"idle_timeout":0,"server_name":"string","s'
            'ervers":[{"host":"string","port":0}],"use_mxedge":true},"vlan_id":'
            '0,"vland_ids":[0],"wxtunnel_id":"string","wxtunnel_remote_id":"str'
            'ing"},"property2":{"disabled":true,"dynamic_vlan":{"default_vlan_i'
            'd":0,"enabled":true,"type":"string","vlans":{"property1":"string",'
            '"property2":"string"}},"enable_mac_auth":true,"forwarding":"all","'
            'mx_tunnel_id":"5f5cac07-0805-46ea-aafd-5c5729042729","mxtunnel_nam'
            'e":"string","port_auth":"none","port_vlan_id":0,"radius_config":{"'
            'acct_interim_interval":0,"acct_servers":[{"host":"string","port":1'
            '813,"secret":"string"}],"auth_servers":[{"host":"string","port":18'
            '12,"secret":"string"}],"auth_servers_retries":3,"auth_servers_time'
            'out":5,"coa_enabled":false,"coa_port":3799,"network":"string","sou'
            'rce_ip":"string"},"radsec":{"enabled":true,"idle_timeout":0,"serve'
            'r_name":"string","servers":[{"host":"string","port":0}],"use_mxedg'
            'e":true},"vlan_id":0,"vland_ids":[0],"wxtunnel_id":"string","wxtun'
            'nel_remote_id":"string"}},"property2":{"property1":{"disabled":tru'
            'e,"dynamic_vlan":{"default_vlan_id":0,"enabled":true,"type":"strin'
            'g","vlans":{"property1":"string","property2":"string"}},"enable_ma'
            'c_auth":true,"forwarding":"all","mx_tunnel_id":"5f5cac07-0805-46ea'
            '-aafd-5c5729042729","mxtunnel_name":"string","port_auth":"none","p'
            'ort_vlan_id":0,"radius_config":{"acct_interim_interval":0,"acct_se'
            'rvers":[{"host":"string","port":1813,"secret":"string"}],"auth_ser'
            'vers":[{"host":"string","port":1812,"secret":"string"}],"auth_serv'
            'ers_retries":3,"auth_servers_timeout":5,"coa_enabled":false,"coa_p'
            'ort":3799,"network":"string","source_ip":"string"},"radsec":{"enab'
            'led":true,"idle_timeout":0,"server_name":"string","servers":[{"hos'
            't":"string","port":0}],"use_mxedge":true},"vlan_id":0,"vland_ids":'
            '[0],"wxtunnel_id":"string","wxtunnel_remote_id":"string"},"propert'
            'y2":{"disabled":true,"dynamic_vlan":{"default_vlan_id":0,"enabled"'
            ':true,"type":"string","vlans":{"property1":"string","property2":"s'
            'tring"}},"enable_mac_auth":true,"forwarding":"all","mx_tunnel_id":'
            '"5f5cac07-0805-46ea-aafd-5c5729042729","mxtunnel_name":"string","p'
            'ort_auth":"none","port_vlan_id":0,"radius_config":{"acct_interim_i'
            'nterval":0,"acct_servers":[{"host":"string","port":1813,"secret":"'
            'string"}],"auth_servers":[{"host":"string","port":1812,"secret":"s'
            'tring"}],"auth_servers_retries":3,"auth_servers_timeout":5,"coa_en'
            'abled":false,"coa_port":3799,"network":"string","source_ip":"strin'
            'g"},"radsec":{"enabled":true,"idle_timeout":0,"server_name":"strin'
            'g","servers":[{"host":"string","port":0}],"use_mxedge":true},"vlan'
            '_id":0,"vland_ids":[0],"wxtunnel_id":"string","wxtunnel_remote_id"'
            ':"string"}}}},"auto_upgrade":{"custom_versions":{"property1":"stri'
            'ng","property2":"string"},"day_of_week":"any","enabled":false,"tim'
            'e_of_day":"string","version":"stable"},"bgp_groups":{"property1":{'
            '"type":"external"},"property2":{"type":"external"}},"blacklist_url'
            '":"string","ble_config":{"beacon_enabled":true,"beacon_rate":0,"be'
            'acon_rate_mode":"default","beam_disabled":[0],"eddystone_uid_adv_p'
            'ower":-100,"eddystone_uid_beams":"string","eddystone_uid_enabled":'
            'true,"eddystone_uid_freq_msec":0,"eddystone_uid_instance":"string"'
            ',"eddystone_uid_namespace":"string","eddystone_url_adv_power":0,"e'
            'ddystone_url_beams":"string","eddystone_url_enabled":true,"eddysto'
            'ne_url_freq_msec":0,"eddystone_url_url":"string","ibeacon_adv_powe'
            'r":-100,"ibeacon_beams":"string","ibeacon_enabled":false,"ibeacon_'
            'freq_msec":0,"ibeacon_major":0,"ibeacon_minor":0,"ibeacon_uuid":"1'
            'f89bc00-d0af-481b-82fe-a6629259a39f","power":9,"power_mode":"strin'
            'g"},"config_auto_revert":false,"created_time":0,"device_updown_thr'
            'eshold":0,"dns_servers":["string"],"dns_suffix":["string"],"enable'
            '_channel_144":false,"engagement":{"dwell_tag_names":{"bounce":"str'
            'ing","engaged":"string","passerby":"string","stationed":"string"},'
            '"dwell_tags":{"bounce":"string","engaged":"string","passerby":"str'
            'ing","stationed":"string"},"hours":{"fri":"string","mon":"string",'
            '"sta":"string","sun":"string","thu":"string","tue":"string","wed":'
            '"string"},"max_dwell":43200,"min_dwell":0},"evpn_options":{"overla'
            'y":{"as":65000},"underlay":{"as_base":65001,"routed_id_prefix":"/2'
            '4","subnet":"10.255.240.0/20"}},"flags":{"property1":"string","pro'
            'perty2":"string"},"for_site":true,"gateway_mgmt":{"app_probing":{"'
            'apps":["string"],"custom_apps":[{"app_type":"string","hostname":["'
            'string"],"name":"string","protocol":"http"}],"enabled":true},"app_'
            'usage":true,"config_revert_timer":10,"security_log_source_address"'
            ':"string","security_log_source_interface":"string"},"id":"498f6eca'
            '-6276-4993-dfeb-53cbbbba6f08","led":{"brightness":0,"enabled":true'
            '},"modified_time":0,"mxedge_mgmt":{"_password":"string","mist_pass'
            'word":"string","root_password":"string"},"mxtunnels":{"ap_subnets"'
            ':["string"],"clusters":[{"name":"string","tunterm_hosts":["string"'
            ']}],"created_time":0,"for_site":true,"hello_interval":60,"hello_re'
            'tries":7,"hosts":["string"],"id":"499f6eca-6276-4993-efeb-53cbbbba'
            '6f08","modified_time":0,"mtu":0,"org_id":"a40f5d1f-d889-42e9-94ea-'
            'b9b33585fc6b","protocol":"udp","radsec":{"acct_servers":[{"host":"'
            'string","port":1813,"secret":"string"}],"auth_servers":[{"host":"s'
            'tring","port":1812,"secret":"string"}],"enabled":true,"use_mxedge"'
            ':true},"site_id":"72771e6a-6f5e-4de4-a5b9-1266c4197811","vlan_ids"'
            ':[0]},"networks":{"property1":{"dns":["string"],"dns_suffix":["str'
            'ing"],"gateway":"string","ospf_interface_type":"string","subnet":"'
            'string","vlan_id":0,"zone":"string"},"property2":{"dns":["string"]'
            ',"dns_suffix":["string"],"gateway":"string","ospf_interface_type":'
            '"string","subnet":"string","vlan_id":0,"zone":"string"}},"ntp_serv'
            'ers":["string"],"occupancy":{"assets_enabled":false,"clients_enabl'
            'ed":true,"min_duration":3000,"sdkclients_enabled":false,"unconnect'
            'ed_clients_enabled":false},"org_id":"a40f5d1f-d889-42e9-94ea-b9b33'
            '585fc6b","ospf_areas":{"property1":{"networks":{"property1":{"auth'
            '_keys":{"property1":"string","property2":"string"},"auth_password"'
            ':"string","auth_type":"none","interface_type":"nbma","passive":fal'
            'se},"property2":{"auth_keys":{"property1":"string","property2":"st'
            'ring"},"auth_password":"string","auth_type":"none","interface_type'
            '":"nbma","passive":false}},"type":"default"},"property2":{"network'
            's":{"property1":{"auth_keys":{"property1":"string","property2":"st'
            'ring"},"auth_password":"string","auth_type":"none","interface_type'
            '":"nbma","passive":false},"property2":{"auth_keys":{"property1":"s'
            'tring","property2":"string"},"auth_password":"string","auth_type":'
            '"none","interface_type":"nbma","passive":false}},"type":"default"}'
            '},"persist_config_on_device":false,"port_usages":{"dynamic":{"mode'
            '":"dynamic","reset_default_when":"link_down","rules":[{"equals":"s'
            'tring","expression":"string","src":"lldp_chassis_id","usage":"stri'
            'ng"}]},"property1":{"all_networks":false,"allow_dhcpd":true,"bypas'
            's_auth_when_server_down":true,"description":"string","disable_auto'
            'neg":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"defau'
            'lt_network":0,"enabled":true,"networks":{"property1":0,"property2"'
            ':0},"type":"standard"},"enable_mac_auth":true,"enable_qos":true,"g'
            'uest_network":"string","mac_auth_only":true,"mac_limit":0,"mode":"'
            'access","mtu":0,"networks":["string"],"persist_mac":false,"poe_dis'
            'abled":false,"port_auth":"string","port_network":"string","rejecte'
            'd_network":true,"speed":"string","storm_control":{"no_broadcast":f'
            'alse,"no_multicast":false,"no_registered_multicast":false,"no_unkn'
            'own_unicast":false,"percentage":80},"stp_edge":true,"voip_network"'
            ':"string"},"property2":{"all_networks":false,"allow_dhcpd":true,"b'
            'ypass_auth_when_server_down":true,"description":"string","disable_'
            'autoneg":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"d'
            'efault_network":0,"enabled":true,"networks":{"property1":0,"proper'
            'ty2":0},"type":"standard"},"enable_mac_auth":true,"enable_qos":tru'
            'e,"guest_network":"string","mac_auth_only":true,"mac_limit":0,"mod'
            'e":"access","mtu":0,"networks":["string"],"persist_mac":false,"poe'
            '_disabled":false,"port_auth":"string","port_network":"string","rej'
            'ected_network":true,"speed":"string","storm_control":{"no_broadcas'
            't":false,"no_multicast":false,"no_registered_multicast":false,"no_'
            'unknown_unicast":false,"percentage":80},"stp_edge":true,"voip_netw'
            'ork":"string"}},"proxy":{"url":"string"},"radio_config":{"ant_gain'
            '_24":0,"ant_gain_5":0,"band_24":{"allow_rrm_disable":true,"ant_gai'
            'n":0,"antenna_mode":"default","bandwidth":20,"channel":0,"channels'
            '":[0],"disabled":true,"power":0,"power_max":0,"power_min":0,"pream'
            'ble":"short","usage":"24"},"band_24_usage":"24","band_5":{"allow_r'
            'rm_disable":true,"ant_gain":0,"antenna_mode":"default","bandwidth"'
            ':20,"channel":0,"channels":[0],"disabled":true,"power":0,"power_ma'
            'x":0,"power_min":0,"preamble":"short","usage":"24"},"band_5_on_24_'
            'radio":{"allow_rrm_disable":true,"ant_gain":0,"antenna_mode":"defa'
            'ult","bandwidth":20,"channel":0,"channels":[0],"disabled":true,"po'
            'wer":0,"power_max":0,"power_min":0,"preamble":"short","usage":"24"'
            '},"scanning_enabled":true},"radius_config":{"acct_interim_interval'
            '":0,"acct_servers":[{"host":"string","port":1813,"secret":"string"'
            '}],"auth_servers":[{"host":"string","port":1812,"secret":"string"}'
            '],"auth_servers_retries":3,"auth_servers_timeout":5,"coa_enabled":'
            'false,"coa_port":3799,"network":"string","source_ip":"string"},"re'
            'mote_syslog":{"enabled":true,"send_to_all_servers":true,"servers":'
            '[{"facility":"authorization","host":"string","port":0,"protocol":"'
            'udp","severity":"any","tag":"string"}]},"report_gatt":false,"rogue'
            '":{"enabled":true,"honeypot_enabled":true,"min_duration":10,"min_r'
            'ssi":-80,"whitelisted_bssids":["string"],"whitelisted_ssids":["str'
            'ing"]},"rtsa":{"app_waking":false,"disable_dead_reckoning":true,"d'
            'isable_pressure_sensor":true,"enabled":true,"track_asset":true},"s'
            'ite_id":"72771e6a-6f5e-4de4-a5b9-1266c4197811","skyatp":{"enabled"'
            ':true,"send_ip_mac_mapping":true},"srx_app":{"enabled":false},"ssh'
            '_keys":["string"],"status_portal":{"enabled":true,"hostnames":["st'
            'ring"]},"switch_matching":{"enable":true,"rules":[{"additional_con'
            'fig_cmds":["string"],"name":"string","port_config":{"property1":{"'
            'ae_disable_lacp":true,"ae_idx":0,"aggregated":false,"description":'
            '"string","disable_autoneg":true,"duplex":"auto","dynamic_usage":"s'
            'tring","esilag":true,"poe_disabled":true,"speed":"auto","usage":"s'
            'tring"},"property2":{"ae_disable_lacp":true,"ae_idx":0,"aggregated'
            '":false,"description":"string","disable_autoneg":true,"duplex":"au'
            'to","dynamic_usage":"string","esilag":true,"poe_disabled":true,"sp'
            'eed":"auto","usage":"string"}},"property1":"string","property2":"s'
            'tring"}]},"switch_mgmt":{"config_revert_timer":10,"mxedge_proxy_ho'
            'st":"string","mxedge_proxy_port":2222,"root_password":"string","us'
            'e_mxedge_proxy":true},"track_anonymous_devices":false,"tunterm_mon'
            'itoring":[{"host":"string","port":0,"protocol":"arp","timeout":300'
            '}],"vars":{"property1":"string","property2":"string"},"vna":{"enab'
            'led":false},"vrf_instances":{"property1":{"extra_routes":{"propert'
            'y1":{"via":"192.168.0.1"},"property2":{"via":"192.168.0.1"}},"netw'
            'orks":["string"]},"property2":{"extra_routes":{"property1":{"via":'
            '"192.168.0.1"},"property2":{"via":"192.168.0.1"}},"networks":["str'
            'ing"]}},"vrrp_groups":{"property1":{"auth_key":"string","auth_pass'
            'word":"string","auth_type":"md5","networks":{"property1":{"ip":"st'
            'ring"},"property2":{"ip":"string"}}},"property2":{"auth_key":"stri'
            'ng","auth_password":"string","auth_type":"md5","networks":{"proper'
            'ty1":{"ip":"string"},"property2":{"ip":"string"}}}},"wan_vna":{"en'
            'abled":false},"watched_station_url":"string","whitelist_url":"stri'
            'ng","wids":{"repeated_auth_failures":{"duration":0,"threshold":0}}'
            ',"wifi":{"cisco_enabled":true,"disable_11k":false,"disable_radios_'
            'when_power_constrained":true,"enable_arp_spoof_check":false,"enabl'
            'e_channel_144":false,"enable_shared_radio_scanning":true,"enable_v'
            'na":false,"enabled":true,"locate_connected":false,"locate_unconnec'
            'ted":false,"mesh_allow_dfs":false,"mesh_enabled":false,"proxy_arp"'
            ':"default"},"wired_vna":{"enabled":false},"zone_occupancy_alert":{'
            '"email_notifiers":["string"],"enabled":false,"threshold":5}}', SiteSetting.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.update_site_settings(site_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"additional_config_cmds":["string"],"analytic":{"enabled":false},'
            '"auto_upgrade":{"custom_versions":{"property1":"string","property2'
            '":"string"},"day_of_week":"any","enabled":false,"time_of_day":"str'
            'ing","version":"stable"},"bgp_groups":{"property1":{"type":"extern'
            'al"},"property2":{"type":"external"}},"ble_config":{"beacon_enable'
            'd":true,"beacon_rate":0,"beacon_rate_mode":"default","beam_disable'
            'd":[0],"eddystone_uid_adv_power":-100,"eddystone_uid_beams":"strin'
            'g","eddystone_uid_enabled":true,"eddystone_uid_freq_msec":0,"eddys'
            'tone_uid_instance":"string","eddystone_uid_namespace":"string","ed'
            'dystone_url_adv_power":0,"eddystone_url_beams":"string","eddystone'
            '_url_enabled":true,"eddystone_url_freq_msec":0,"eddystone_url_url"'
            ':"string","ibeacon_adv_power":-100,"ibeacon_beams":"string","ibeac'
            'on_enabled":false,"ibeacon_freq_msec":0,"ibeacon_major":0,"ibeacon'
            '_minor":0,"ibeacon_uuid":"1f89bc00-d0af-481b-82fe-a6629259a39f","p'
            'ower":9,"power_mode":"string"},"config_auto_revert":false,"created'
            '_time":0,"device_updown_threshold":0,"dns_servers":["string"],"dns'
            '_suffix":["string"],"enable_channel_144":false,"engagement":{"dwel'
            'l_tag_names":{"bounce":"string","engaged":"string","passerby":"str'
            'ing","stationed":"string"},"dwell_tags":{"bounce":"string","engage'
            'd":"string","passerby":"string","stationed":"string"},"hours":{"fr'
            'i":"string","mon":"string","sta":"string","sun":"string","thu":"st'
            'ring","tue":"string","wed":"string"},"max_dwell":43200,"min_dwell"'
            ':0},"evpn_options":{"overlay":{"as":0},"underlay":{"as_base":0,"su'
            'bnet":"string"}},"flags":{"property1":"string","property2":"string'
            '"},"for_site":true,"gateway_mgmt":{"app_usage":true,"config_revert'
            '_timer":10},"id":"458f6ec2-6276-4993-bfeb-53abbbba6f08","led":{"br'
            'ightness":0,"enabled":true},"modified_time":0,"mxtunnels":{"proper'
            'ty1":{"ap_subnets":["string"],"clusters":[{"name":"string","tunter'
            'm_hosts":["string"]}],"created_time":0,"for_site":true,"hello_inte'
            'rval":60,"hello_retries":7,"hosts":["string"],"id":"457f6ec3-6276-'
            '4993-bfeb-53cbbbba6f08","modified_time":0,"mtu":0,"org_id":"a40f5d'
            '1f-d889-42e9-94ea-b9b33585fc6b","protocol":"udp","radsec":{"acct_s'
            'ervers":[{"host":"string","port":1813,"secret":"string"}],"auth_se'
            'rvers":[{"host":"string","port":1812,"secret":"string"}],"enabled"'
            ':true,"use_mxedge":true},"site_id":"72771e6a-6f5e-4de4-a5b9-1266c4'
            '197811","vlan_ids":[0]},"property2":{"ap_subnets":["string"],"clus'
            'ters":[{"name":"string","tunterm_hosts":["string"]}],"created_time'
            '":0,"for_site":true,"hello_interval":60,"hello_retries":7,"hosts":'
            '["string"],"id":"456f6ec4-6276-4993-bfeb-53cbbbba6f08","modified_t'
            'ime":0,"mtu":0,"org_id":"a40f5d1f-d889-42e9-94ea-b9b33585fc6b","pr'
            'otocol":"udp","radsec":{"acct_servers":[{"host":"string","port":18'
            '13,"secret":"string"}],"auth_servers":[{"host":"string","port":181'
            '2,"secret":"string"}],"enabled":true,"use_mxedge":true},"site_id":'
            '"72771e6a-6f5e-4de4-a5b9-1266c4197811","vlan_ids":[0]}},"networks"'
            ':{"property1":{"dns":["string"],"dns_suffix":["string"],"gateway":'
            '"string","ospf_interface_type":"string","subnet":"string","vlan_id'
            '":0,"zone":"string"},"property2":{"dns":["string"],"dns_suffix":["'
            'string"],"gateway":"string","ospf_interface_type":"string","subnet'
            '":"string","vlan_id":0,"zone":"string"}},"ntp_servers":["string"],'
            '"occupancy":{"assets_enabled":false,"clients_enabled":true,"min_du'
            'ration":3000,"sdkclients_enabled":false,"unconnected_clients_enabl'
            'ed":false},"org_id":"a40f5d1f-d889-42e9-94ea-b9b33585fc6b","ospf_a'
            'reas":{"property1":{"networks":{"property1":{"auth_keys":{"propert'
            'y1":"string","property2":"string"},"auth_password":"string","auth_'
            'type":"none","interface_type":"nbma","passive":false},"property2":'
            '{"auth_keys":{"property1":"string","property2":"string"},"auth_pas'
            'sword":"string","auth_type":"none","interface_type":"nbma","passiv'
            'e":false}},"type":"default"},"property2":{"networks":{"property1":'
            '{"auth_keys":{"property1":"string","property2":"string"},"auth_pas'
            'sword":"string","auth_type":"none","interface_type":"nbma","passiv'
            'e":false},"property2":{"auth_keys":{"property1":"string","property'
            '2":"string"},"auth_password":"string","auth_type":"none","interfac'
            'e_type":"nbma","passive":false}},"type":"default"}},"persist_confi'
            'g_on_device":false,"port_usages":{"dynamic":{"mode":"dynamic","rul'
            'es":[{"equals":"string","expression":"string","src":"lldp_chassis_'
            'id","usage":"string"}]},"property1":{"all_networks":false,"bypass_'
            'auth_when_server_down":true,"description":"string","disable_autone'
            'g":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"default'
            '_network":0,"enabled":true,"networks":{"property1":0,"property2":0'
            '},"type":"standard"},"enable_mac_auth":true,"enable_qos":true,"gue'
            'st_network":"string","mac_limit":0,"mode":"access","mtu":0,"networ'
            'ks":["string"],"persist_mac":false,"poe_disabled":false,"port_auth'
            '":"string","port_network":"string","speed":"string","storm_control'
            '":{"no_broadcast":false,"no_multicast":false,"no_registered_multic'
            'ast":false,"no_unknown_unicast":false,"percentage":80},"stp_edge":'
            'true,"voip_network":"string"},"property2":{"all_networks":false,"b'
            'ypass_auth_when_server_down":true,"description":"string","disable_'
            'autoneg":false,"disabled":false,"duplex":"auto","dynamic_vlan":{"d'
            'efault_network":0,"enabled":true,"networks":{"property1":0,"proper'
            'ty2":0},"type":"standard"},"enable_mac_auth":true,"enable_qos":tru'
            'e,"guest_network":"string","mac_limit":0,"mode":"access","mtu":0,"'
            'networks":["string"],"persist_mac":false,"poe_disabled":false,"por'
            't_auth":"string","port_network":"string","speed":"string","storm_c'
            'ontrol":{"no_broadcast":false,"no_multicast":false,"no_registered_'
            'multicast":false,"no_unknown_unicast":false,"percentage":80},"stp_'
            'edge":true,"voip_network":"string"}},"proxy":{"url":"string"},"rad'
            'io_config":{"ant_gain_24":0,"ant_gain_5":0,"band_24":{"allow_rrm_d'
            'isable":true,"ant_gain":0,"antenna_mode":"default","bandwidth":20,'
            '"channel":0,"channels":[0],"disabled":true,"power":0,"power_max":0'
            ',"power_min":0,"preamble":"short","usage":"24"},"band_24_usage":"2'
            '4","band_5":{"allow_rrm_disable":true,"ant_gain":0,"antenna_mode":'
            '"default","bandwidth":20,"channel":0,"channels":[0],"disabled":tru'
            'e,"power":0,"power_max":0,"power_min":0,"preamble":"short","usage"'
            ':"24"},"band_5_on_24_radio":{"allow_rrm_disable":true,"ant_gain":0'
            ',"antenna_mode":"default","bandwidth":20,"channel":0,"channels":[0'
            '],"disabled":true,"power":0,"power_max":0,"power_min":0,"preamble"'
            ':"short","usage":"24"},"scanning_enabled":true},"radius_config":{"'
            'acct_interim_interval":0,"acct_servers":[{"host":"string","port":1'
            '813,"secret":"string"}],"auth_servers":[{"host":"string","port":18'
            '12,"secret":"string"}],"auth_servers_retries":3,"auth_servers_time'
            'out":5},"remote_syslog":{"enabled":true,"send_to_all_servers":true'
            ',"servers":[{"facility":"any","host":"string","port":0,"protocol":'
            '"udp","severity":"alert","tag":"string"}]},"report_gatt":false,"ro'
            'gue":{"enabled":true,"honeypot_enabled":true,"min_duration":10,"mi'
            'n_rssi":-80,"whitelisted_bssids":["string"],"whitelisted_ssids":["'
            'string"]},"rtsa":{"app_waking":false,"disable_dead_reckoning":true'
            ',"disable_pressure_sensor":true,"enabled":true,"track_asset":true}'
            ',"site_id":"72771e6a-6f5e-4de4-a5b9-1266c4197811","skyatp":{"enabl'
            'ed":true,"send_ip_mac_mapping":true},"ssh_keys":["string"],"status'
            '_portal":{"enabled":true,"hostnames":["string"]},"switch_matching"'
            ':{"enable":true,"rules":[{"additional_config_cmds":["string"],"nam'
            'e":"string","port_config":{"property1":{"ae_disable_lacp":true,"ae'
            '_idx":0,"aggregated":false,"description":"string","esilag":true,"u'
            'sage":"string"},"property2":{"ae_disable_lacp":true,"ae_idx":0,"ag'
            'gregated":false,"description":"string","esilag":true,"usage":"stri'
            'ng"}},"property1":"string","property2":"string"}]},"switch_mgmt":{'
            '"config_revert_timer":10,"root_password":"string"},"track_anonymou'
            's_devices":false,"vars":{"property1":"string","property2":"string"'
            '},"vrf_instances":{"property1":{"extra_routes":{"property1":{"via"'
            ':"192.168.0.1"},"property2":{"via":"192.168.0.1"}},"networks":["st'
            'ring"]},"property2":{"extra_routes":{"property1":{"via":"192.168.0'
            '.1"},"property2":{"via":"192.168.0.1"}},"networks":["string"]}},"v'
            'rrp_groups":{"property1":{"auth_key":"string","auth_password":"str'
            'ing","auth_type":"md5","networks":{"property1":{"ip":"string"},"pr'
            'operty2":{"ip":"string"}}},"property2":{"auth_key":"string","auth_'
            'password":"string","auth_type":"md5","networks":{"property1":{"ip"'
            ':"string"},"property2":{"ip":"string"}}}},"wids":{"repeated_auth_f'
            'ailures":{"duration":0,"threshold":0}},"wifi":{"cisco_enabled":tru'
            'e,"disable_11k":false,"disable_radios_when_power_constrained":true'
            ',"enable_arp_spoof_check":false,"enable_channel_144":false,"enable'
            '_shared_radio_scanning":true,"enable_vna":false,"enabled":true,"lo'
            'cate_connected":false,"locate_unconnected":false,"mesh_allow_dfs":'
            'false,"mesh_enabled":false,"proxy_arp":"default"},"zone_occupancy_'
            'alert":{"email_notifiers":["string"],"enabled":false,"threshold":5'
            '}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Delete Site Blacklist Station Clients
    def test_delete_site_wireless_clients_blocklist(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.delete_site_wireless_clients_blocklist(site_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # This endpoint is to provide list of client macs for annotation blacklist.
    #
    #Retrieve the current clients list `blacklist_url` under Site:Setting
    def test_create_site_wireless_clients_blocklist(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}', ModelObjectMacsArrayString.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.create_site_wireless_clients_blocklist(site_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Delete Site Watched Station Clients
    def test_delete_site_watched_stations(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.delete_site_watched_stations(site_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # This endpoint is to provide list of client macs for annotation as  watched station.
    #
    #Retrieve the current clients list from  `watched_station_url` under Site:Setting
    def test_create_site_watched_stations(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}', ModelObjectMacsArrayString.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.create_site_watched_stations(site_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Delete Site Whitelist Station Clients
    def test_delete_site_wireless_clients_allowlist(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.delete_site_wireless_clients_allowlist(site_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # This endpoint is to provide list of client macs for annotation as whitelist.
    #
    #Retrieve the current clients list from `whitelist_url` under Site:Setting
    def test_create_site_wireless_clients_allowlist(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}', ModelObjectMacsArrayString.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.create_site_wireless_clients_allowlist(site_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"macs":["18-65-90-de-f4-c6","84-89-ad-5d-69-0d"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

