# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from mistapi.api_helper import APIHelper
from mistapi.models.device_switch_vc import DeviceSwitchVc
from mistapi.models.api_v_1_sites_devices_vc_vc_port_request import ApiV1SitesDevicesVcVcPortRequest


class SitesDevicesWiredVirtualChassisControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(SitesDevicesWiredVirtualChassisControllerTests, cls).setUpClass()
        cls.controller = cls.client.sites_devices_wired_virtual_chassis
        cls.response_catcher = cls.controller.http_call_back

    # When all the member switches of VC are removed and only member ID 0 is left, the cloud would detect this situation and automatically changes the single switch to non-VC role.
    #
    #For some unexpected cases that the VC is gone and disconncted, the API below could be used to change the state of VC’s switches to be standalone. After it is executed, all the switches will be shown as standalone switches under Inventory.
    def test_delete_site_virtual_chassis(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        device_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.delete_site_virtual_chassis(site_id, device_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # Get VC Status
    #
    #The API returns a combined view of the VC status which includes topology and stats_
    def test_get_site_device_virtual_chassis(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        device_id = '000000ab-00ab-00ab-00ab-0000000000ab'

        # Perform the API call through the SDK function
        result = self.controller.get_site_device_virtual_chassis(site_id, device_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":{"members":[{"mac":"string","member":0,"vc_ports":["string"]'
            ',"vc_role":"master"}],"op":"add"}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # For models (e.g. EX3400 and up) having dedicated VC ports, it is easier to form a VC by just connecting cables with the dedicated VC ports. Cloud will detect the new VC and update the inventory.
    #
    #In case that the user would like to choose the dedicated switch as a VC master. Or for EX2300-C-12P and EX2300-C-12T which doesn’t have dedicated VC ports, below are procedures to automate the VC creation:
    #
    #1. Power on the switch that is choosen as the VC master first. And the powering on the other member switches.
    #2. Claim or adopt all these switches under the same organization’s Inventory
    #3. Assign these switches into the same Site
    #4. Invoke vc command on the switch choosen to be the VC master. For EX2300-C-12P, VC ports will be created automatically.
    #5. Connect the cables to the VC ports for these switches
    #6. Wait for the VC to be formed. The Org’s inventory will be updated for the new VC.
    def test_create_site_virtual_chassis(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        device_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"members":[{"mac":"aff827549235","vc_ports":["xe-0/1/0"]},{"mac":'
            '"8396cd006c8c","vc_ports":["xe-0/1/0","xe-0/1/1"]},{"mac":"8396cd0'
            '0888c","vc_ports":["xe-0/1/0"]}]}', DeviceSwitchVc.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.create_site_virtual_chassis(site_id, device_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":{"members":[{"mac":"string","member":0,"vc_ports":["string"]'
            ',"vc_role":"master"}],"op":"add"}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # The VC creation and adding member switch API will update the device’s virtual chassis config which is applied after VC is formed to create JUNOS pre-provisioned virtual chassis configuration.
    #
    ### Change to use preprovisioned VC
    #To switch the VC to use preprovisioned VC, enable preprovisioned in virtual_chassis config. Both vc_role master and backup will be matched to routing-engine role in Junos preprovisioned VC config.
    #
    #In this config, fpc0 has to be the same as the mac of device_id. Use renumber if you want to replace fpc0 which involves device_id change.
    #
    #Notice: to configure preprovisioned VC, every member of the VC must be in the inventory.
    #
    ### Add new members
    #For models (e.g. EX4300 and up) having dedicated VC ports, it is easier to add new member switches into a VC by just connecting cables with the dedicated VC ports. Cloud will detect the new members and update the inventory.
    #
    #For EX2300 VC, adding new members requires to follow the procedures below:
    #1. Powering on the new member switches and ensuring cables are not connected to any VC ports.
    #2. Claim or adopt all new member switches under the VC’s organization Inventory
    #3. Assign all new member switches to the same Site as the VC
    #4. Invoke vc command to add switches to the VC.
    #5. Connect the cables to the VC ports for these switches
    #6. After a while, the Org’s Inventory shows this new switches has been added into the VC.
    #
    ### Removing member switch
    #To remove a member switch from the VC, following the procedures below:
    #
    #1. Ensuring the VC is connected to the cloud first
    #2. Unplug the cable from the VC port of the switch
    #3. Waiting for the VC state (vc_state) of this switch is changed to not-present
    #4. Invoke update_vc with remove to remove this switch from the VC
    #5. The Org’s Inventory shows the switch is removed.
    #
    #Please notice that member ID 0 (fpc0) cannot be removed. When a VC has two switches left, unpluging the cable may result in the situation that fpc0 becomes a line card (LC). When this situation is happened, please re-plug in the cable, wait for both switches becoming present (show virtual-chassis) and then removing the cable again.
    #
    ### Renumber a member switch
    #When a member switch doesn’t work properly and needed to be replaced, the renumber API could be used. The following two types of renumber are supported:
    #
    #1. Replace a non-fpc0 member switch
    #2. Replace fpc0. When fpc0 is relaced, PAPI device config and JUNOS config will be both updated.
    #
    #For renumber to work, the following procedures are needed: 
    #1. Ensuring the VC is connected to the cloud and the state of the member switch to be replaced must be non present. 
    #2. Adding the new member switch to the VC 
    #3. Waiting for the VC state (vc_state) of this VC to be updated to API server 
    #4. Invoke vc with renumber to replace the new member switch from fpc X to
    def test_update_site_virtual_chassis_member(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        device_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"members":[{"mac":"aff827549235","member":0,"vc_ports":["xe-0/1/1'
            '"]},{"mac":"aff827549235","member":2,"vc_ports":["xe-0/1/1"]},{"ma'
            'c":"8396cd00777c","vc_ports":["xe-0/1/0"]},{"mac":"8396cd00888c","'
            'vc_ports":["xe-0/1/0"]}],"op":"add"}', DeviceSwitchVc.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.update_site_virtual_chassis_member(site_id, device_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":{"members":[{"mac":"string","member":0,"vc_ports":["string"]'
            ',"vc_role":"master"}],"op":"add"}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Set VC port
    def test_set_site_vc_port(self):
        # Parameters for the API call
        site_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        device_id = '000000ab-00ab-00ab-00ab-0000000000ab'
        body = APIHelper.json_deserialize('{"members":[{"member":0,"vc_ports":["xe-0/1/1"]},{"member":2,"vc_p'
            'orts":["xe-0/1/1"]}],"op":"delete"}', ApiV1SitesDevicesVcVcPortRequest.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.set_site_vc_port(site_id, device_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


