# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class AcctServer(object):

    """Implementation of the 'acct_server' model.

    TODO: type model description here.

    Attributes:
        host (string): ip / hostname of RADIUS server
        keywrap_enabled (bool): TODO: type description here.
        keywrap_format (string): TODO: type description here.
        keywrap_kek (string): TODO: type description here.
        keywrap_mack (string): TODO: type description here.
        port (int): Acct port of RADIUS server
        secret (string): secret of RADIUS server

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "host": 'host',
        "port": 'port',
        "secret": 'secret',
        "keywrap_enabled": 'keywrap_enabled',
        "keywrap_format": 'keywrap_format',
        "keywrap_kek": 'keywrap_kek',
        "keywrap_mack": 'keywrap_mack'
    }

    _optionals = [
        'keywrap_enabled',
        'keywrap_format',
        'keywrap_kek',
        'keywrap_mack',
    ]

    def __init__(self,
                 host=None,
                 port=1813,
                 secret=None,
                 keywrap_enabled=APIHelper.SKIP,
                 keywrap_format=APIHelper.SKIP,
                 keywrap_kek=APIHelper.SKIP,
                 keywrap_mack=APIHelper.SKIP):
        """Constructor for the AcctServer class"""

        # Initialize members of the class
        self.host = host 
        if keywrap_enabled is not APIHelper.SKIP:
            self.keywrap_enabled = keywrap_enabled 
        if keywrap_format is not APIHelper.SKIP:
            self.keywrap_format = keywrap_format 
        if keywrap_kek is not APIHelper.SKIP:
            self.keywrap_kek = keywrap_kek 
        if keywrap_mack is not APIHelper.SKIP:
            self.keywrap_mack = keywrap_mack 
        self.port = port 
        self.secret = secret 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        host = dictionary.get("host") if dictionary.get("host") else None
        port = dictionary.get("port") if dictionary.get("port") else 1813
        secret = dictionary.get("secret") if dictionary.get("secret") else None
        keywrap_enabled = dictionary.get("keywrap_enabled") if "keywrap_enabled" in dictionary.keys() else APIHelper.SKIP
        keywrap_format = dictionary.get("keywrap_format") if dictionary.get("keywrap_format") else APIHelper.SKIP
        keywrap_kek = dictionary.get("keywrap_kek") if dictionary.get("keywrap_kek") else APIHelper.SKIP
        keywrap_mack = dictionary.get("keywrap_mack") if dictionary.get("keywrap_mack") else APIHelper.SKIP
        # Return an object of this model
        return cls(host,
                   port,
                   secret,
                   keywrap_enabled,
                   keywrap_format,
                   keywrap_kek,
                   keywrap_mack)
