# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Action7Enum(object):

    """Implementation of the 'Action7' enum.

    type of action, allow / block

    Attributes:
        ALLOW: TODO: type description here.
        BLOCK: TODO: type description here.

    """

    ALLOW = 'allow'

    BLOCK = 'block'
