# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ApiV1MspsOrgsRequest(object):

    """Implementation of the 'Api V1 Msps Orgs Request' model.

    TODO: type model description here.

    Attributes:
        op (Op3Enum): TODO: type description here.
        org_ids (list of string): list of org_id

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "op": 'op',
        "org_ids": 'org_ids'
    }

    def __init__(self,
                 op=None,
                 org_ids=None):
        """Constructor for the ApiV1MspsOrgsRequest class"""

        # Initialize members of the class
        self.op = op 
        self.org_ids = org_ids 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        op = dictionary.get("op") if dictionary.get("op") else None
        org_ids = dictionary.get("org_ids") if dictionary.get("org_ids") else None
        # Return an object of this model
        return cls(op,
                   org_ids)
