# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper
from mistapi.models.targets_1 import Targets1


class ApiV1SitesSsrUpgradeResponse(object):

    """Implementation of the 'Api V1 Sites Ssr Upgrade Response' model.

    TODO: type model description here.

    Attributes:
        channel (string): TODO: type description here.
        device_type (string): TODO: type description here.
        id (string): TODO: type description here.
        status (string): TODO: type description here.
        targets (Targets1): TODO: type description here.
        versions (object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "channel": 'channel',
        "id": 'id',
        "status": 'status',
        "targets": 'targets',
        "versions": 'versions',
        "device_type": 'device_type'
    }

    _optionals = [
        'device_type',
    ]

    def __init__(self,
                 channel=None,
                 id=None,
                 status=None,
                 targets=None,
                 versions=None,
                 device_type=APIHelper.SKIP):
        """Constructor for the ApiV1SitesSsrUpgradeResponse class"""

        # Initialize members of the class
        self.channel = channel 
        if device_type is not APIHelper.SKIP:
            self.device_type = device_type 
        self.id = id 
        self.status = status 
        self.targets = targets 
        self.versions = versions 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        channel = dictionary.get("channel") if dictionary.get("channel") else None
        id = dictionary.get("id") if dictionary.get("id") else None
        status = dictionary.get("status") if dictionary.get("status") else None
        targets = Targets1.from_dictionary(dictionary.get('targets')) if dictionary.get('targets') else None
        versions = dictionary.get("versions") if dictionary.get("versions") else None
        device_type = dictionary.get("device_type") if dictionary.get("device_type") else APIHelper.SKIP
        # Return an object of this model
        return cls(channel,
                   id,
                   status,
                   targets,
                   versions,
                   device_type)
