# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ApiV1LoginOauthResponse(object):

    """Implementation of the 'Api V1 Login Oauth Response' model.

    TODO: type model description here.

    Attributes:
        authorization_url (string): TODO: type description here.
        client_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "authorization_url": 'authorization_url',
        "client_id": 'client_id'
    }

    def __init__(self,
                 authorization_url=None,
                 client_id=None):
        """Constructor for the ApiV1LoginOauthResponse class"""

        # Initialize members of the class
        self.authorization_url = authorization_url 
        self.client_id = client_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        authorization_url = dictionary.get("authorization_url") if dictionary.get("authorization_url") else None
        client_id = dictionary.get("client_id") if dictionary.get("client_id") else None
        # Return an object of this model
        return cls(authorization_url,
                   client_id)
