# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class AppProbing(object):

    """Implementation of the 'AppProbing' model.

    TODO: type model description here.

    Attributes:
        apps (list of string): app-keys from /api/v1/const/applications

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "apps": 'apps'
    }

    _optionals = [
        'apps',
    ]

    def __init__(self,
                 apps=APIHelper.SKIP):
        """Constructor for the AppProbing class"""

        # Initialize members of the class
        if apps is not APIHelper.SKIP:
            self.apps = apps 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        apps = dictionary.get("apps") if dictionary.get("apps") else APIHelper.SKIP
        # Return an object of this model
        return cls(apps)
