# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AuthenticationProtocol1Enum(object):

    """Implementation of the 'AuthenticationProtocol1' enum.

    can be set for non-mist-nac config when `enable_mac_auth`==`true`

    Attributes:
        PAP: TODO: type description here.
        EAPPEAP: TODO: type description here.
        EAPMD5: TODO: type description here.

    """

    PAP = 'pap'

    EAPPEAP = 'eap-peap'

    EAPMD5 = 'eap-md5'
