# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Bandwidth5Enum(object):

    """Implementation of the 'Bandwidth5' enum.

    channel width for the band

    Attributes:
        ENUM_20: TODO: type description here.
        ENUM_40: TODO: type description here.
        ENUM_80: TODO: type description here.
        ENUM_160: TODO: type description here.

    """

    ENUM_20 = 20

    ENUM_40 = 40

    ENUM_80 = 80

    ENUM_160 = 160
