# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BandwidthEnum(object):

    """Implementation of the 'Bandwidth' enum.

    channel width for the band, 20 / 40 / 80 / 160, 80 is only applicable for
    band_5 and 160 is only for band_6, ignored if channel is 0

    Attributes:
        ENUM_20: TODO: type description here.
        ENUM_40: TODO: type description here.
        ENUM_80: TODO: type description here.

    """

    ENUM_20 = 20

    ENUM_40 = 40

    ENUM_80 = 80
