# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BfdProfileEnum(object):

    """Implementation of the 'BfdProfile' enum.

    TODO: type enum description here.

    Attributes:
        LTE: TODO: type description here.
        BROADBAND: TODO: type description here.

    """

    LTE = 'lte'

    BROADBAND = 'broadband'
