# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Cloudshark(object):

    """Implementation of the 'Cloudshark' model.

    TODO: type model description here.

    Attributes:
        apitoken (string): TODO: type description here.
        url (string): if using CS Enteprise

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "apitoken": 'apitoken',
        "url": 'url'
    }

    _optionals = [
        'apitoken',
        'url',
    ]

    def __init__(self,
                 apitoken=APIHelper.SKIP,
                 url=APIHelper.SKIP):
        """Constructor for the Cloudshark class"""

        # Initialize members of the class
        if apitoken is not APIHelper.SKIP:
            self.apitoken = apitoken 
        if url is not APIHelper.SKIP:
            self.url = url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        apitoken = dictionary.get("apitoken") if dictionary.get("apitoken") else APIHelper.SKIP
        url = dictionary.get("url") if dictionary.get("url") else APIHelper.SKIP
        # Return an object of this model
        return cls(apitoken,
                   url)
