# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Cluster(object):

    """Implementation of the 'Cluster' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        tunterm_hosts (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "tunterm_hosts": 'tunterm_hosts'
    }

    _optionals = [
        'name',
        'tunterm_hosts',
    ]

    def __init__(self,
                 name=APIHelper.SKIP,
                 tunterm_hosts=APIHelper.SKIP):
        """Constructor for the Cluster class"""

        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name 
        if tunterm_hosts is not APIHelper.SKIP:
            self.tunterm_hosts = tunterm_hosts 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        tunterm_hosts = dictionary.get("tunterm_hosts") if dictionary.get("tunterm_hosts") else APIHelper.SKIP
        # Return an object of this model
        return cls(name,
                   tunterm_hosts)
