# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Content1(object):

    """Implementation of the 'Content1' model.

    TODO: type model description here.

    Attributes:
        group (string): refer to group_name under access
        security_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "group": 'group',
        "security_name": 'security_name'
    }

    _optionals = [
        'group',
        'security_name',
    ]

    def __init__(self,
                 group=APIHelper.SKIP,
                 security_name=APIHelper.SKIP):
        """Constructor for the Content1 class"""

        # Initialize members of the class
        if group is not APIHelper.SKIP:
            self.group = group 
        if security_name is not APIHelper.SKIP:
            self.security_name = security_name 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        group = dictionary.get("group") if dictionary.get("group") else APIHelper.SKIP
        security_name = dictionary.get("security_name") if dictionary.get("security_name") else APIHelper.SKIP
        # Return an object of this model
        return cls(group,
                   security_name)
