# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Datum(object):

    """Implementation of the 'Datum' model.

    TODO: type model description here.

    Attributes:
        range (list of float): TODO: type description here.
        value (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "value": 'value',
        "range": 'range'
    }

    _optionals = [
        'range',
    ]

    def __init__(self,
                 value=None,
                 range=APIHelper.SKIP):
        """Constructor for the Datum class"""

        # Initialize members of the class
        if range is not APIHelper.SKIP:
            self.range = range 
        self.value = value 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        value = dictionary.get("value") if dictionary.get("value") else None
        range = dictionary.get("range") if dictionary.get("range") else APIHelper.SKIP
        # Return an object of this model
        return cls(value,
                   range)
