# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DayOfWeekEnum(object):

    """Implementation of the 'DayOfWeek' enum.

    TODO: type enum description here.

    Attributes:
        ANY: TODO: type description here.
        MON: TODO: type description here.
        TUE: TODO: type description here.
        WED: TODO: type description here.
        THU: TODO: type description here.
        FRI: TODO: type description here.
        SAT: TODO: type description here.
        SUN: TODO: type description here.

    """

    ANY = 'any'

    MON = 'mon'

    TUE = 'tue'

    WED = 'wed'

    THU = 'thu'

    FRI = 'fri'

    SAT = 'sat'

    SUN = 'sun'
