# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Distinct16Enum(object):

    """Implementation of the 'distinct16' enum.

    TODO: type enum description here.

    Attributes:
        AP: TODO: type description here.
        WCID: TODO: type description here.
        SSID: TODO: type description here.
        ENUM_WLAN_ID APP: TODO: type description here.
        DEVICE_MAC: TODO: type description here.
        SRC_IP: TODO: type description here.
        PORT_ID: TODO: type description here.
        APP: TODO: type description here.
        CATEGORY: TODO: type description here.
        SERVICE: TODO: type description here.

    """

    AP = 'ap'

    WCID = 'wcid'

    SSID = 'ssid'

    ENUM_WLAN_ID_APP = 'wlan_id app'

    DEVICE_MAC = 'device_mac'

    SRC_IP = 'src_ip'

    PORT_ID = 'port_id'

    APP = 'app'

    CATEGORY = 'category'

    SERVICE = 'service'
