# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Distinct14Enum(object):

    """Implementation of the 'distinct14' enum.

    TODO: type enum description here.

    Attributes:
        BSSID: TODO: type description here.
        SSID: TODO: type description here.
        AP: TODO: type description here.
        TYPE: TODO: type description here.

    """

    BSSID = 'bssid'

    SSID = 'ssid'

    AP = 'ap'

    ENUM_TYPE = 'type'
