# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Distinct2Enum(object):

    """Implementation of the 'distinct2' enum.

    TODO: type enum description here.

    Attributes:
        STATUS: TODO: type description here.
        TYPE: TODO: type description here.
        ORG_ID: TODO: type description here.

    """

    STATUS = 'status'

    ENUM_TYPE = 'type'

    ORG_ID = 'org_id'
