# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Distinct7Enum(object):

    """Implementation of the 'distinct7' enum.

    TODO: type enum description here.

    Attributes:
        SSID: TODO: type description here.
        WLAN_ID: TODO: type description here.
        AP: TODO: type description here.
        MAC: TODO: type description here.
        CLIENT_FAMILY: TODO: type description here.
        CLIENT_MANUFACTURE: TODO: type description here.
        CLIENT_MODEL: TODO: type description here.
        CLIENT_OS: TODO: type description here.

    """

    SSID = 'ssid'

    WLAN_ID = 'wlan_id'

    AP = 'ap'

    MAC = 'mac'

    CLIENT_FAMILY = 'client_family'

    CLIENT_MANUFACTURE = 'client_manufacture'

    CLIENT_MODEL = 'client_model'

    CLIENT_OS = 'client_os'
