# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Distinct5Enum(object):

    """Implementation of the 'distinct5' enum.

    TODO: type enum description here.

    Attributes:
        SSID: TODO: type description here.
        AP: TODO: type description here.
        IP: TODO: type description here.
        VLAN: TODO: type description here.
        HOSTNAME: TODO: type description here.
        OS: TODO: type description here.
        MODEL: TODO: type description here.
        DEVICE: TODO: type description here.

    """

    SSID = 'ssid'

    AP = 'ap'

    IP = 'ip'

    VLAN = 'vlan'

    HOSTNAME = 'hostname'

    OS = 'os'

    MODEL = 'model'

    DEVICE = 'device'
