# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EthertypeEnum(object):

    """Implementation of the 'Ethertype' enum.

    TODO: type enum description here.

    Attributes:
        ETHERNET: TODO: type description here.
        VLAN: TODO: type description here.

    """

    ETHERNET = 'ethernet'

    VLAN = 'vlan'
