# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ForwardingEnum(object):

    """Implementation of the 'Forwarding' enum.

    TODO: type enum description here.

    Attributes:
        ALL: TODO: type description here.
        LIMITED: TODO: type description here.
        WXTUNNEL: TODO: type description here.
        MXTUNNEL: TODO: type description here.
        SITE_MXEDGE: TODO: type description here.

    """

    ALL = 'all'

    LIMITED = 'limited'

    WXTUNNEL = 'wxtunnel'

    MXTUNNEL = 'mxtunnel'

    SITE_MXEDGE = 'site_mxedge'
