# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Fwupdate(object):

    """Implementation of the 'Fwupdate' model.

    TODO: type model description here.

    Attributes:
        progress (int): TODO: type description here.
        status (string): TODO: type description here.
        status_id (int): TODO: type description here.
        timestamp (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "progress": 'progress',
        "status": 'status',
        "status_id": 'status_id',
        "timestamp": 'timestamp'
    }

    _optionals = [
        'progress',
        'status',
        'status_id',
        'timestamp',
    ]

    def __init__(self,
                 progress=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 status_id=APIHelper.SKIP,
                 timestamp=APIHelper.SKIP):
        """Constructor for the Fwupdate class"""

        # Initialize members of the class
        if progress is not APIHelper.SKIP:
            self.progress = progress 
        if status is not APIHelper.SKIP:
            self.status = status 
        if status_id is not APIHelper.SKIP:
            self.status_id = status_id 
        if timestamp is not APIHelper.SKIP:
            self.timestamp = timestamp 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        progress = dictionary.get("progress") if dictionary.get("progress") else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else APIHelper.SKIP
        status_id = dictionary.get("status_id") if dictionary.get("status_id") else APIHelper.SKIP
        timestamp = dictionary.get("timestamp") if dictionary.get("timestamp") else APIHelper.SKIP
        # Return an object of this model
        return cls(progress,
                   status,
                   status_id,
                   timestamp)
