# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IkeModeEnum(object):

    """Implementation of the 'IkeMode' enum.

    Only if:
    * `provider`== `custom-ipsec`

    Attributes:
        MAIN: TODO: type description here.
        AGGRESSIVE: TODO: type description here.

    """

    MAIN = 'main'

    AGGRESSIVE = 'aggressive'
