# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InfoEnum(object):

    """Implementation of the 'Info' enum.

    optional choice: process, outbound-ssh, and full (default)

    Attributes:
        PROCESS: TODO: type description here.
        OUTBOUNDSSH: TODO: type description here.
        MESSAGES: TODO: type description here.
        CODEDUMPS: TODO: type description here.
        FULL: TODO: type description here.
        VARLOGS: TODO: type description here.
        JMALOGS: TODO: type description here.

    """

    PROCESS = 'process'

    OUTBOUNDSSH = 'outbound-ssh'

    MESSAGES = 'messages'

    CODEDUMPS = 'code-dumps'

    FULL = 'full'

    VARLOGS = 'var-logs'

    JMALOGS = 'jma-logs'
