# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Metric(object):

    """Implementation of the 'Metric' model.

    TODO: type model description here.

    Attributes:
        api_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_name": 'apiName'
    }

    _optionals = [
        'api_name',
    ]

    def __init__(self,
                 api_name=APIHelper.SKIP):
        """Constructor for the Metric class"""

        # Initialize members of the class
        if api_name is not APIHelper.SKIP:
            self.api_name = api_name 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        api_name = dictionary.get("apiName") if dictionary.get("apiName") else APIHelper.SKIP
        # Return an object of this model
        return cls(api_name)
