# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class MistNac(object):

    """Implementation of the 'MistNac' model.

    enable mist_nac to use radsec

    Attributes:
        enabled (bool): TODO: type description here.
        network (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "enabled": 'enabled',
        "network": 'network'
    }

    _optionals = [
        'enabled',
        'network',
    ]

    def __init__(self,
                 enabled=APIHelper.SKIP,
                 network=APIHelper.SKIP):
        """Constructor for the MistNac class"""

        # Initialize members of the class
        if enabled is not APIHelper.SKIP:
            self.enabled = enabled 
        if network is not APIHelper.SKIP:
            self.network = network 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        enabled = dictionary.get("enabled") if "enabled" in dictionary.keys() else APIHelper.SKIP
        network = dictionary.get("network") if dictionary.get("network") else APIHelper.SKIP
        # Return an object of this model
        return cls(enabled,
                   network)
