# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Proto1Enum(object):

    """Implementation of the 'Proto1' enum.

    TODO: type enum description here.

    Attributes:
        A: TODO: type description here.
        B: TODO: type description here.
        G: TODO: type description here.
        N: TODO: type description here.
        AC: TODO: type description here.
        AX: TODO: type description here.

    """

    A = 'a'

    B = 'b'

    G = 'g'

    N = 'n'

    AC = 'ac'

    AX = 'ax'
