# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Proxy1(object):

    """Implementation of the 'Proxy1' model.

    TODO: type model description here.

    Attributes:
        url (string): Proxy Configuration to talk to Mist

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": 'url'
    }

    _optionals = [
        'url',
    ]

    def __init__(self,
                 url=APIHelper.SKIP):
        """Constructor for the Proxy1 class"""

        # Initialize members of the class
        if url is not APIHelper.SKIP:
            self.url = url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        url = dictionary.get("url") if dictionary.get("url") else APIHelper.SKIP
        # Return an object of this model
        return cls(url)
