# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PullupEnum(object):

    """Implementation of the 'Pullup' enum.

    the type of pull-up the pin uses (internal, external, none), default none

    Attributes:
        INTERNAL: TODO: type description here.
        EXTERNAL: TODO: type description here.
        NONE: TODO: type description here.

    """

    INTERNAL = 'internal'

    EXTERNAL = 'external'

    NONE = 'none'
