# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class ReportDuration(object):

    """Implementation of the 'ReportDuration' model.

    TODO: type model description here.

    Attributes:
        interval (int): TODO: type description here.
        max_age (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "interval": 'interval',
        "max_age": 'max_age'
    }

    _optionals = [
        'interval',
        'max_age',
    ]

    def __init__(self,
                 interval=APIHelper.SKIP,
                 max_age=APIHelper.SKIP):
        """Constructor for the ReportDuration class"""

        # Initialize members of the class
        if interval is not APIHelper.SKIP:
            self.interval = interval 
        if max_age is not APIHelper.SKIP:
            self.max_age = max_age 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        interval = dictionary.get("interval") if dictionary.get("interval") else APIHelper.SKIP
        max_age = dictionary.get("max_age") if dictionary.get("max_age") else APIHelper.SKIP
        # Return an object of this model
        return cls(interval,
                   max_age)
