# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Role4Enum(object):

    """Implementation of the 'Role4' enum.

    TODO: type enum description here.

    Attributes:
        ACCESS: TODO: type description here.
        AGGREGATION: TODO: type description here.

    """

    ACCESS = 'access'

    AGGREGATION = 'aggregation'
