# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RrmNodeOrderEnum(object):

    """Implementation of the 'RrmNodeOrder' enum.

    Used in rrm to determine whether to start upgrade from fringe or center
    AP’s

    Attributes:
        FRINGE_TO_CENTER: TODO: type description here.
        CENTER_TO_FRINGE: TODO: type description here.

    """

    FRINGE_TO_CENTER = 'fringe_to_center'

    CENTER_TO_FRINGE = 'center_to_fringe'
