# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Scope1Enum(object):

    """Implementation of the 'Scope1' enum.

    TODO: type enum description here.

    Attributes:
        SITE: TODO: type description here.
        AP: TODO: type description here.
        CLIENT: TODO: type description here.
        SWITCH: TODO: type description here.
        DEVICE: TODO: type description here.
        MXEDGE: TODO: type description here.

    """

    SITE = 'site'

    AP = 'ap'

    CLIENT = 'client'

    SWITCH = 'switch'

    DEVICE = 'device'

    MXEDGE = 'mxedge'
