# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SpeedEnum(object):

    """Implementation of the 'Speed' enum.

    TODO: type enum description here.

    Attributes:
        AUTO: TODO: type description here.
        ENUM_10M: TODO: type description here.
        ENUM_100M: TODO: type description here.
        ENUM_1G: TODO: type description here.
        ENUM_25G: TODO: type description here.
        ENUM_5G: TODO: type description here.

    """

    AUTO = 'auto'

    ENUM_10M = '10m'

    ENUM_100M = '100m'

    ENUM_1G = '1g'

    ENUM_25G = '2.5g'

    ENUM_5G = '5g'
