# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StateEnum(object):

    """Implementation of the 'State' enum.

    TODO: type enum description here.

    Attributes:
        IDLE: TODO: type description here.
        CONNECT: TODO: type description here.
        ACTIVE: TODO: type description here.
        OPEN_SENT: TODO: type description here.
        OPEN_CONFIG: TODO: type description here.
        ESTABLISHED: TODO: type description here.

    """

    IDLE = 'idle'

    CONNECT = 'connect'

    ACTIVE = 'active'

    OPEN_SENT = 'open_sent'

    OPEN_CONFIG = 'open_config'

    ESTABLISHED = 'established'
