# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StpRoleEnum(object):

    """Implementation of the 'stp_role' enum.

    TODO: type enum description here.

    Attributes:
        DESIGNATED: TODO: type description here.
        BACKUP: TODO: type description here.
        ALTERNATE: TODO: type description here.
        ROOT: TODO: type description here.
        ROOTPREVENTED: TODO: type description here.

    """

    DESIGNATED = 'designated'

    BACKUP = 'backup'

    ALTERNATE = 'alternate'

    ROOT = 'root'

    ROOTPREVENTED = 'root-prevented'
