# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Summary(object):

    """Implementation of the 'Summary' model.

    TODO: type model description here.

    Attributes:
        num_ap_assigned (int): TODO: type description here.
        num_inv_assigned (int): TODO: type description here.
        num_map_assigned (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "num_ap_assigned": 'num_ap_assigned',
        "num_inv_assigned": 'num_inv_assigned',
        "num_map_assigned": 'num_map_assigned'
    }

    def __init__(self,
                 num_ap_assigned=None,
                 num_inv_assigned=None,
                 num_map_assigned=None):
        """Constructor for the Summary class"""

        # Initialize members of the class
        self.num_ap_assigned = num_ap_assigned 
        self.num_inv_assigned = num_inv_assigned 
        self.num_map_assigned = num_map_assigned 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        num_ap_assigned = dictionary.get("num_ap_assigned") if dictionary.get("num_ap_assigned") else None
        num_inv_assigned = dictionary.get("num_inv_assigned") if dictionary.get("num_inv_assigned") else None
        num_map_assigned = dictionary.get("num_map_assigned") if dictionary.get("num_map_assigned") else None
        # Return an object of this model
        return cls(num_ap_assigned,
                   num_inv_assigned,
                   num_map_assigned)
