# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class SyntheticTest(object):

    """Implementation of the 'SyntheticTest' model.

    TODO: type model description here.

    Attributes:
        urls (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "urls": 'urls'
    }

    _optionals = [
        'urls',
    ]

    def __init__(self,
                 urls=APIHelper.SKIP):
        """Constructor for the SyntheticTest class"""

        # Initialize members of the class
        if urls is not APIHelper.SKIP:
            self.urls = urls 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        urls = dictionary.get("urls") if dictionary.get("urls") else APIHelper.SKIP
        # Return an object of this model
        return cls(urls)
