# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TuntermOtherIpConfigs(object):

    """Implementation of the 'TuntermOtherIpConfigs' model.

    TODO: type model description here.

    Attributes:
        ip (string): TODO: type description here.
        netmask (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ip": 'ip',
        "netmask": 'netmask'
    }

    def __init__(self,
                 ip=None,
                 netmask=None):
        """Constructor for the TuntermOtherIpConfigs class"""

        # Initialize members of the class
        self.ip = ip 
        self.netmask = netmask 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        ip = dictionary.get("ip") if dictionary.get("ip") else None
        netmask = dictionary.get("netmask") if dictionary.get("netmask") else None
        # Return an object of this model
        return cls(ip,
                   netmask)
