# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type31Enum(object):

    """Implementation of the 'Type31' enum.

    TODO: type enum description here.

    Attributes:
        RELAY: TODO: type description here.

    """

    RELAY = 'relay'
