# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type57Enum(object):

    """Implementation of the 'type57' enum.

    TODO: type enum description here.

    Attributes:
        HONEYPOT: TODO: type description here.
        LAN: TODO: type description here.
        OTHERS: TODO: type description here.
        SPOOF: TODO: type description here.

    """

    HONEYPOT = 'honeypot'

    LAN = 'lan'

    OTHERS = 'others'

    SPOOF = 'spoof'
