# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type23Enum(object):

    """Implementation of the 'Type23' enum.

    device type

    Attributes:
        AP: TODO: type description here.
        SWITCH: TODO: type description here.
        GATEWAY: TODO: type description here.

    """

    AP = 'ap'

    SWITCH = 'switch'

    GATEWAY = 'gateway'
