# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class Versions(object):

    """Implementation of the 'Versions' model.

    TODO: type model description here.

    Attributes:
        mxagent (string): TODO: type description here.
        tuntnerm (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mxagent": 'mxagent',
        "tuntnerm": 'tuntnerm'
    }

    _optionals = [
        'mxagent',
        'tuntnerm',
    ]

    def __init__(self,
                 mxagent=APIHelper.SKIP,
                 tuntnerm=APIHelper.SKIP):
        """Constructor for the Versions class"""

        # Initialize members of the class
        if mxagent is not APIHelper.SKIP:
            self.mxagent = mxagent 
        if tuntnerm is not APIHelper.SKIP:
            self.tuntnerm = tuntnerm 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        mxagent = dictionary.get("mxagent") if dictionary.get("mxagent") else APIHelper.SKIP
        tuntnerm = dictionary.get("tuntnerm") if dictionary.get("tuntnerm") else APIHelper.SKIP
        # Return an object of this model
        return cls(mxagent,
                   tuntnerm)
