# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper
from mistapi.models.major_version_1 import MajorVersion1


class VersionCompliance1(object):

    """Implementation of the 'VersionCompliance1' model.

    version compliance score, major version for gateway, type

    Attributes:
        major_version (dict): TODO: type description here.
        score (float): TODO: type description here.
        mtype (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "major_version": 'major_version',
        "score": 'score',
        "mtype": 'type'
    }

    _optionals = [
        'major_version',
        'score',
        'mtype',
    ]

    def __init__(self,
                 major_version=APIHelper.SKIP,
                 score=APIHelper.SKIP,
                 mtype=APIHelper.SKIP):
        """Constructor for the VersionCompliance1 class"""

        # Initialize members of the class
        if major_version is not APIHelper.SKIP:
            self.major_version = major_version 
        if score is not APIHelper.SKIP:
            self.score = score 
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        major_version = MajorVersion1.from_dictionary(dictionary.get('major_version')) if 'major_version' in dictionary.keys() else APIHelper.SKIP
        score = dictionary.get("score") if dictionary.get("score") else APIHelper.SKIP
        mtype = dictionary.get("type") if dictionary.get("type") else APIHelper.SKIP
        # Return an object of this model
        return cls(major_version,
                   score,
                   mtype)
